# This is a basic workflow that is manually triggered

name: Deploy Docker Images to AWS ECR

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::086726293497:role/Github-Action
        role-duration-seconds: 1000
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image for training ml model to Amazon ECR
      id: training
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ml
        IMAGE_TAG: training
      run: |
        docker build --file ./ml_ops/src/training/Dockerfile -t training .
        docker tag training:latest 086726293497.dkr.ecr.eu-cental-1.amazonaws.com/training:latest
        docker push 086726293497.dkr.ecr.eu-central-1.amazonaws.com/training:latest
    - name: Build, tag, and push image for generating inference from pre-trained ml model to Amazon ECR
      id: inference
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ml
        IMAGE_TAG: infernce
      run: |
        docker build --file ./ml_ops/src/inference/Dockerfile -t inference .
        docker tag inference:latest 086726293497.dkr.ecr.eu-cental-1.amazonaws.com/inference:latest
        docker push 086726293497.dkr.ecr.eu-central-1.amazonaws.com/inference:latest
