# This is a basic workflow that is manually triggered

name: Start inference service

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Start Inference Service
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ml_ops/infrastructure

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::086726293497:role/Github-Action
        role-duration-seconds: 1000
        aws-region: eu-central-1

    - name: Run docker container to start inference service for generating predictions from pre-trained machine learning mdoel
      id: start_inference_service
      run: docker run --file ./ml_ops/src/inference/Dockerfile
