# This is a basic workflow that is manually triggered

name: Start training

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Start Training
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::086726293497:role/Github-Action
        role-duration-seconds: 500
        aws-region: eu-central-1

    - name: Run docker container to start training of a machine learning model
      id: start_training
      run: docker run --file ./ml_ops/src/training/Dockerfile
